### ISSUE TITLE
Missing Robot icon resource for Symbiont

### ISSUE THREAD

**Issue by Veritania** [OpenPerpetuum/perpetuum-killboard#23]
There's a robot icon that isn't being shown
https://killboard.openperpetuum.com/kill/3249
![firefox_IIVUUcfTsn](https://user-images.githubusercontent.com/6807104/115852808-c4a92a80-a428-11eb-92fd-ac9c56fda02f.png)

**Comment by MikeJeffers** [comment]
Fixed
